"""agregar bloqueo de usuarios, ocultamiento de contenido y tabla reportes

Revision ID: 8925203b4def
Revises: c282a8dc9bb1
Create Date: 2026-09-11 19:49:41.829856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8925203b4def'
down_revision: Union[str, Sequence[str], None] = 'c282a8dc9bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reportante_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.Column('perdida_id', sa.Integer(), nullable=True),
    sa.Column('avistamiento_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('contenido_oculto', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('usuario_bloqueado', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('utc_timestamp()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['avistamiento_id'], ['avistamientos.id'], ),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['perdida_id'], ['perdidas.id'], ),
    sa.ForeignKeyConstraint(['reportante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('avistamientos', sa.Column('oculto', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('mascotas', sa.Column('oculta', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('perdidas', sa.Column('oculta', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('usuarios', sa.Column('bloqueado', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('usuarios', sa.Column('bloqueado_por_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('bloqueado_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('desbloqueado_por_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('desbloqueado_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['bloqueado_por_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['desbloqueado_por_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'desbloqueado_at')
    op.drop_column('usuarios', 'desbloqueado_por_id')
    op.drop_column('usuarios', 'bloqueado_at')
    op.drop_column('usuarios', 'bloqueado_por_id')
    op.drop_column('usuarios', 'bloqueado')
    op.drop_column('perdidas', 'oculta')
    op.drop_column('mascotas', 'oculta')
    op.drop_column('avistamientos', 'oculto')
    op.drop_table('reportes')
    # ### end Alembic commands ###
