"""crear tabla mensajes

Revision ID: b3543d2b0d12
Revises: 0e82840c68c1
Create Date: 2026-08-22 15:20:21.268776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3543d2b0d12'
down_revision: Union[str, Sequence[str], None] = '0e82840c68c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes')
    # ### end Alembic commands ###
