"""crear tablas mascotas y fotos_mascota

Revision ID: 14de71374f52
Revises: 9758f9210998
Create Date: 2026-08-21 10:25:06.162060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14de71374f52'
down_revision: Union[str, Sequence[str], None] = '9758f9210998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.String(length=20), nullable=True),
    sa.Column('vacunas', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('castrada', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('foto_principal_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_mascota',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos_mascota')
    op.drop_table('mascotas')
    # ### end Alembic commands ###
