"""crear tabla solicitudes

Revision ID: 0e82840c68c1
Revises: 14de71374f52
Create Date: 2026-08-22 11:54:05.716724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e82840c68c1'
down_revision: Union[str, Sequence[str], None] = '14de71374f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('adoptante_id', sa.Integer(), nullable=False),
    sa.Column('dueno_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adoptante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
