"""crear tablas perdidas y avistamientos

Revision ID: 1343e3446e4d
Revises: b33c8b287ce8
Create Date: 2026-08-23 15:09:47.309051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1343e3446e4d'
down_revision: Union[str, Sequence[str], None] = 'b33c8b287ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perdidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=False),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.Column('fecha_perdida', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='Desaparecida', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avistamientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perdida_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perdida_id'], ['perdidas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avistamientos')
    op.drop_table('perdidas')
    # ### end Alembic commands ###
