"""agregar tabla conversaciones y reestructurar mensajes

Revision ID: 1f22d05a30f5
Revises: 1343e3446e4d
Create Date: 2026-08-23 16:38:00.952944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f22d05a30f5'
down_revision: Union[str, Sequence[str], None] = '1343e3446e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('avistamiento_id', sa.Integer(), nullable=True),
    sa.Column('participante_a_id', sa.Integer(), nullable=False),
    sa.Column('participante_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avistamiento_id'], ['avistamientos.id'], ),
    sa.ForeignKeyConstraint(['participante_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['participante_b_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avistamiento_id'),
    sa.UniqueConstraint('solicitud_id')
    )
    op.add_column('mensajes', sa.Column('conversacion_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('mensajes_ibfk_3'), 'mensajes', type_='foreignkey')
    op.drop_constraint(op.f('mensajes_ibfk_2'), 'mensajes', type_='foreignkey')
    op.create_foreign_key(None, 'mensajes', 'conversaciones', ['conversacion_id'], ['id'])
    op.drop_column('mensajes', 'receptor_id')
    op.drop_column('mensajes', 'solicitud_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('solicitud_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('mensajes', sa.Column('receptor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.create_foreign_key(op.f('mensajes_ibfk_2'), 'mensajes', 'usuarios', ['receptor_id'], ['id'])
    op.create_foreign_key(op.f('mensajes_ibfk_3'), 'mensajes', 'solicitudes', ['solicitud_id'], ['id'])
    op.drop_column('mensajes', 'conversacion_id')
    op.drop_table('conversaciones')
    # ### end Alembic commands ###
