"""cambiar historial_sesiones a DATETIME UTC y agregar indice en ended_at

Revision ID: c282a8dc9bb1
Revises: 5298a7075e46
Create Date: 2026-09-07 16:54:49.107515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c282a8dc9bb1'
down_revision: Union[str, Sequence[str], None] = '5298a7075e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historial_sesiones', 'started_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('current_timestamp()'),
               server_default=None)
    op.alter_column('historial_sesiones', 'ended_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_historial_sesiones_ended_at'), 'historial_sesiones', ['ended_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_sesiones_ended_at'), table_name='historial_sesiones')
    op.alter_column('historial_sesiones', 'ended_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('historial_sesiones', 'started_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###
